 - name-var: $BASE
   sintax: $BASE = {X 500.0, Y 0.0, Z 0.0, A 0.0, B 0.0, C 90.0}
   discriptions: |
      это рабочая система координат, в которой задаются все декартовы точки (POS, FRAME) в программе.
      По умолчанию $BASE = $WORLD (мировая система).
      Вы можете переопределить $BASE, чтобы, например, привязать программу к детали на конвейере.
      Все движения (LIN, PTP и т.д.) интерпретируются относительно текущего $BASE.
      📐 Тип:
      FRAME (структура: X, Y, Z, A, B, C)
      Чтение и запись (вы можете менять)
      💡 Назначение:
      Определяет, где находится начало и ориентация вашей рабочей зоны относительно мира.

      📏 Единицы:
      X, Y, Z — в миллиметрах,
      A, B, C — в градусах (углы поворота: обычно A = вращение вокруг X, B — вокруг Y, C — вокруг Z).
   example: |
     ; Переместить BASE на 500 мм вперёд по X и повернуть на 90° вокруг Z
      $BASE = {X 500.0, Y 0.0, Z 0.0, A 0.0, B 0.0, C 90.0}

      ; Теперь точка P1 задаётся относительно этой новой BASE
      LIN {X 100, Y 0, Z 0, A 0, B 0, C 0}  ; = 600 мм по X в мировой системе
      ⚠️ Изменение $BASE вызывает advance run stop — выполнение приостанавливается до синхронизации. 

 - name-var: $BASE_C
   sintax: $BASE_C.X - $BASE.X
   discriptions: |
     📐 Тип:
     FRAME
     Только чтение (write-protected)
     Отражает реальное текущее положение BASE, с учётом всех динамических поправок (например, от RSI или внешних коррекций).
     💡 Когда использовать?
     Для диагностики: сравнить $BASE и $BASE_C — большая разница = коррекция активна.
     В обработчиках прерываний или безопасных приложениях.
   example: |
    ; Проверить, не сместился ли BASE (например, из-за RSI)
      IF ABS($BASE_C.X - $BASE.X) > 5.0 THEN
      MsgNotify("BASE сместился более чем на 5 мм")
      ENDIF

 - name-var: $BASE_KIN
   sintax: |
     $ET1_NAME = "CONVEYOR"
     $ET1_AX   = {E1}  ; внешняя ось E1 участвует в BASE
   discriptions: |
     📐 Тип:
     CHAR[29] (строка до 29 символов)
     Только чтение
     💡 Назначение:
     Если вы используете внешнюю кинематику (например, робот на линейной оси E1, и BASE привязан к этой оси), то:

     $BASE_KIN содержит имя этой кинематической системы и список осей, участвующих в преобразовании.
     🛠 Где настраивается?
     В Machine Data
   example: |
     DECL CHAR out_msg[128]

     out_msg[] = $BASE_KIN[]
     MsgNotify(out_msg)